Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "95",
        "--memory", "1024",
      ]
  end
  config.vm.define "telegramTunnelClient" do |client|
      client.vm.hostname = "telegramTunnelClient"
      client.vm.network :private_network, ip: "192.168.69.42"
  end

  config.vm.define "telegramTunnelServer" do |server|
      server.vm.hostname = "telegramTunnelServer"
      server.vm.network :private_network, ip: "192.168.69.42"
  end


  config.vm.provision "provision_script", type: "shell", path: "provision.sh", run: "once"
  config.vm.provision "file", source: "teletun_tdlib_ratelimited.py", destination: "$HOME/teletun_tdlib_ratelimited.py", run: "once"
end


